- name: build server
  command: go build -v -o /usr/local/bin/pagcasa-server backend/cmd/server/main.go
  args:
    chdir: /usr/local/OSURuralBroadbandMeasurement/repo
  notify:
    - restart server

# restart systemd service
- name: restart server
  systemd:
    name: PAgCASA-server
    state: restarted
    enabled: true
    daemon_reload: true

- name: permissions server
  file:
    path: /usr/local/bin/pagcasa-server
    owner: backend-server
    group: backend-server
    mode: "755"
