- name: build server
  command: go build -v backend/cmd/server/main.go -o /usr/local/OSURuralBroadbandMeasurement/server
  args:
    chdir: /usr/local/OSURuralBroadbandMeasurement/repo
  notify:
    - restart server

# restart systemd service TODO verify this is working as expected
- name: restart server
  systemd:
    name: PAgCASA-server
    state: restarted
    enabled: true
    action: restart
