- name: Install git and golang from yum repo
  yum:
    name:
      - git
      - golang
    state: present

# create backend-server user
- name: Create backend-server user
  user:
    name: backend-server
    state: present

- name: Create /var/www/services/backend
  file:
    path: /var/www/services/backend
    state: directory
    owner: backend-server
    group: backend-server
    mode: "755"

- name: Clone OSURuralBroadbandMeasurement
  git:
    repo: https://github.com/PAgCASA/OSURuralBroadbandMeasurement
    version: main
    dest: /usr/local/OSURuralBroadbandMeasurement/repo
    depth: 1
  register: git_result
  notify:
    - build server

- name: make sure server exists
  command: "echo 'server file does not exist'"
  args:
    creates: /var/www/services/backend/server
  notify:
    - build server
    - restart server

# install systemd service
- name: Install systemd service
  template:
    src: server.service
    dest: /usr/lib/systemd/system/PAgCASA-server.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart server

# make sure that we actually have an executable to run before we try to start the service
- name: Flush handlers
  meta: flush_handlers

- name: Make sure server is enabled and started
  systemd:
    name: PAgCASA-server
    state: started
    enabled: true
