---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  # - name: Example assertion
  #  assert:
  #    that: true
  - name: Can we connect to the backend server?
    uri:
      url: http://localhost:8080/api/v0/submitSpeedTest
      method: POST
      body: "{}"  # TODO will need to eventually use something along the lines of "{{ lookup('file','issue.json') }}"
      body_format: json
