name: Ansible Lint

on: 
  push:
    branches: [ main ]
    paths:
      - 'infra/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible 'ansible-lint[community,yamllint]'
    - name: Lint playbook
      run: |
        cd infra/
        ansible-playbook -i test-hosts site.yml --syntax-check
        ansible-lint site.yml
